apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-data-grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi