apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
      - name: password-generator
        image: docker.io/ahsanemon/password-generator
        ports:
        - name: pg-port
          containerPort: 5000
