apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data-prometheus
  namespace: monitoring
  labels:
    type: local
    app: prometheus-deployment
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/prometheus"